---
- name: add mysql user and install mysql
  hosts: mysql
  max_fail_percentage: 2
  tasks:
        - name: copy file from control machine to remote host
          unarchive: src=./mysql_install_packages/mysql-5.6.38-linux-glibc2.12-x86_64.tar.gz dest=/tmp/ copy=yes

        - name: install mysql
          shell: mv /tmp/mysql-5.6.38-linux-glibc2.12-x86_64 /usr/local/mysql56
          register: shell_output

        - name: add user
          shell: useradd mysql
          register: shell_output

        - name: config path
          shell: echo "export PATH=/usr/local/mysql56/bin:$PATH" >> /root/.bashrc;source /root/.bashrc
          register: shell_output
