---
- name: set monitor
  hosts: mysql
#  max_fail_percentage: 2
  tasks:

        - name: 安装基础包
          yum: pkg={{ item }} state=installed
          with_items:
            - libselinux-python

        - name: copy file from control machine to remote host
          unarchive: src=./mysql_install_packages/openfalcon.tar.gz dest=/usr/local copy=yes
          tags:
             - unarchive

        - name: sed falcon
          shell: sed -i "s/__hostip__/{{ ansible_ssh_host }}/g" /usr/local/openfalcon/agent/cfg.json
          register: result

        - name: sed mymon
          shell: sed -i "s/__hostip__/{{ ansible_ssh_host }}/g" /usr/local/openfalcon/mymon/etc/mon.cfg
          register: result

        - name: sed mymon
          shell: sed -i "s/__port__/{{ mysql_port }}/g" /usr/local/openfalcon/mymon/etc/mon.cfg
          register: result

        - name: start falcon
          shell: "/usr/local/openfalcon/agent/falcon-agent -c /usr/local/openfalcon/agent/cfg.json &> /usr/local/openfalcon/agent/falcon.log & "
          async: 1
          poll: 0

        - name: set crontal
          cron:
            name: mymon
            job: /usr/local/openfalcon/mymon/mymon -c /usr/local/openfalcon/mymon/etc/mon.cfg