---
- name: set monitor
  hosts: other
  tasks:

        - name: stop falcon
          shell: kill -9 $(netstat -nltp|grep falcon-agen|grep :1988|awk -F " " '{ print $7}'|awk -F "/" '{print $1}')
          tags:
            - stopfalcon
          ignore_errors: True

        - name: sed address
          shell: sed -i "s/127.0.0.1:1988/127.0.0.1:1998/g" /usr/local/openfalcon-0.2/mymon/etc/mon.cfg
          register: result

        - name: sed port
          shell: sed -i "s/port=3306/port={{ mysql_port }}/g" /usr/local/openfalcon-0.2/mymon/etc/mon.cfg
          register: result

        - name: set crontal
          cron:
            name: mymon_update
            job: /usr/local/openfalcon-0.2/mymon/mymon -c /usr/local/openfalcon-0.2/mymon/etc/mon.cfg
          tags:
            - cron